<MatchPage>:
    cols: 1
    size_hint_y: None
    spacing: 10

<Match>:
    size_hint_y: None
    height: 120
    cols: 1
    BackgroundLabel:
        id: title
        background_color: 0.185, 0.202, 0.235, 1

    GridLayout:
        cols: 3
        BackgroundLabel:
            background_color: 0.185, 0.202, 0.235, 1
            id: bet_home
        TextInput:
            id: input_home
            text: ""

        Button:
            id: submit_home
            text: "Domicile"
            on_press: root.bet(self.text)

    GridLayout:
        id: draw
        cols: 3
        BackgroundLabel:
            background_color: 0.185, 0.202, 0.235, 1
            id: bet_draw
        TextInput:
            id: input_draw
            text: ""
        Button:
            id: submit_draw
            text: "Nul"
            on_press: root.bet(self.text)


    GridLayout:
        cols: 3
        BackgroundLabel:
            background_color: 0.185, 0.202, 0.235, 1
            id: bet_away
        TextInput:
            id: input_away
            text: ""
        Button:
            id: submit_away
            text: "Extérieur"
            on_press: root.bet(self.text)